## Project 1 Mid-Term

#### Heena Parekh
#### 3/23/26

#### Project Description
This project focuses on retail sales, and is modeled somewhat after Lab 4. I took a SQL database and a NoSQL database about retail sales, and through an ETL pipeline, I created a data mart, and verified this through SQL queries. 

#### Overall Process
In order to complete this project, I started by finding the 2 datasets online. I was able to then download the SQL dataset as a .csv file, and the NoSQL database was on Atlas (MongoDB). In terms of my actual code, I started by importing all the libraries I needed, creating connection variables to connect to MySQL Workbench & MongoDB/Atlas, and defining important functions. Then, through my code, I loaded the dataset contained in the .csv file into MySQL, did some preliminary data cleaning & added in a revenue column, as I would need it later, & extracted the data into the MySQL database. Next, I extracted the NoSQL dataset from my MongoDB cluster by connecting to Atlas. I then transformed the data to make it cleaner & better suited to this project & my needs. Finally, I loaded everything to my Data Warehouse in MySQL Workbench, and then wrote some simple & complex SQL queries to ensure the entire process was completed correctly.

## 1) Setup

#### Import the Necessary Libraries

In [2]:
import os
import json
import numpy
import datetime
import certifi
import pandas as pd

import pymongo
import sqlalchemy
from sqlalchemy import create_engine, text

In [3]:
print(f"Running SQL Alchemy Version: {sqlalchemy.__version__}")
print(f"Running PyMongo Version: {pymongo.__version__}")

Running SQL Alchemy Version: 2.0.34
Running PyMongo Version: 4.16.0

#### Declare & Assign Connection Variables for the MongoDB Server, the MySQL Server & Databases with which You'll be Working

In [4]:
mysql_args = {
    "uid" : "root",
    "pwd" : "Passw0rd$26",
    "hostname" : "localhost",  
    "dbname" : "retail_data"
}

mongodb_args = {
    "user_name" : "heenaparekh",
    "password" : "passw0rd_38",
    "cluster_name" : "midtermprojectcluster",
    "cluster_subnet" : "redd3lv",
    "cluster_location" : "mongodb.net",
    "db_name" : "sample_supplies"
}

#mongodb+srv://heenaparekh:passw0rd_38@midtermprojectcluster.redd3lv.mongodb.net/?appName=MidtermProjectCluster

#### Define Functions for Getting Data From and Setting Data Into Databases

In [5]:
def get_sql_dataframe(sql_query, **args):
    '''Create a connection to the MySQL database'''
    conn_str = f"mysql+pymysql://{args['uid']}:{args['pwd']}@{args['hostname']}/{args['dbname']}"
    sqlEngine = create_engine(conn_str, pool_recycle=3600)
    connection = sqlEngine.connect()
    
    '''Invoke the pd.read_sql() function to query the database, and fill a Pandas DataFrame.'''
    dframe = pd.read_sql(text(sql_query), connection);
    connection.close()
    
    return dframe
    

def set_dataframe(df, table_name, pk_column, db_operation, **args):
    '''Create a connection to the MySQL database'''
    conn_str = f"mysql+pymysql://{args['uid']}:{args['pwd']}@{args['hostname']}/{args['dbname']}"
    sqlEngine = create_engine(conn_str, pool_recycle=3600)
    db_connection = sqlEngine.connect()
    
    '''Invoke the Pandas DataFrame .to_sql( ) function to either create, or append to, a table'''
    if db_operation in ['insert', 'update']:
        if db_operation.lower() == "insert":
            df.to_sql(table_name, con=db_connection, index=False, if_exists='replace')
            db_connection.execute(text(f"ALTER TABLE {table_name} ADD {pk_column} INT AUTO_INCREMENT PRIMARY KEY FIRST;"))
                    
        elif db_operation.lower() == "update":
            df.to_sql(table_name, con=db_connection, index=False, if_exists='append')

    else:
        print("The value supplied to the 'db_operation' parameter must be either 'insert' or 'update'.")
    
    db_connection.close()


def get_mongo_client(**args):
    '''Validate proper input'''
    if args["cluster_location"] not in ['atlas', 'local']:
        raise Exception("You must specify either 'atlas' or 'local' for the cluster_location parameter.")
    
    else:
        if args["cluster_location"] == "atlas":
            connect_str = f"mongodb+srv://{args['user_name']}:{args['password']}@"
            connect_str += f"{args['cluster_name']}.{args['cluster_subnet']}.mongodb.net"
            client = pymongo.MongoClient(connect_str, tlsCAFile=certifi.where())
            
        elif args["cluster_location"] == "local":
            client = pymongo.MongoClient("mongodb://localhost:27017/")
        
    return client


def get_mongo_dataframe(mongo_client, db_name, collection, query):
    '''Query MongoDB, and fill a python list with documents to create a DataFrame'''
    db = mongo_client[db_name]
    dframe = pd.DataFrame(list(db[collection].find(query)))
    dframe.drop(['_id'], axis=1, inplace=True)
    mongo_client.close()
    
    return dframe


def set_mongo_collections(mongo_client, db_name, data_directory, json_files):
    db = mongo_client[db_name]
    
    for file in json_files:
        db.drop_collection(file)
        json_file = os.path.join(data_directory, json_files[file])
        with open(json_file, 'r') as openfile:
            json_object = json.load(openfile)
            file = db[file]
            result = file.insert_many(json_object)
        
    mongo_client.close()

## 2) Load CSV file into MySQL

In [6]:
# Load CSV file & Preview
data_dir = os.path.join(os.getcwd(), 'DS-2002/Midterm Project')
data_file = os.path.join(data_dir, 'online_retail.csv')

df_retail = pd.read_csv(data_file, header=0)
df_retail.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [7]:
#Checking to make sure all collumns are properly in the df
print(df_retail.columns)

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')

In [8]:
# Drop nulls
df_retail = df_retail.dropna(subset=['CustomerID', 'Description'])

# Convert date
df_retail['InvoiceDate'] = pd.to_datetime(df_retail['InvoiceDate'])

# Create revenue column
df_retail['Revenue'] = df_retail['Quantity'] * df_retail['UnitPrice']

In [9]:
engine = create_engine("mysql+pymysql://root:Passw0rd$26@localhost/retail_data")
df_retail.to_sql('online_retail', engine, if_exists='replace', index=False)

406829

## 3) Extract from MySQL

In [10]:
sql_query = "SELECT * FROM online_retail;"
df_sql = get_sql_dataframe(sql_query, **mysql_args)

df_sql.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34

## 4) Extract from MongoDB

In [11]:
client = pymongo.MongoClient(
    "mongodb://heenaparekh:passw0rd_38@ac-8rnymft-shard-00-00.redd3lv.mongodb.net:27017,ac-8rnymft-shard-00-01.redd3lv.mongodb.net:27017,ac-8rnymft-shard-00-02.redd3lv.mongodb.net:27017/?ssl=true&replicaSet=atlas-clutwk-shard-0&authSource=admin&appName=MidtermProjectCluster",
    tlsCAFile=certifi.where()
)

db = client["sample_supplies"]
collection = db["sales"]

df_mongo = pd.DataFrame(list(collection.find()))
df_mongo.head()

,_id,saleDate,items,storeLocation,customer,couponUsed,purchaseMethod
0,5bd761dcae323e45a93ccffa,2016-08-15 04:05:03.298,"[{'name': 'laptop', 'tags': ['electronics', 's...",San Diego,"{'gender': 'F', 'age': 40, 'email': 'elusekjiv...",True,In store
1,5bd761dcae323e45a93cd000,2015-05-15 13:43:24.561,"[{'name': 'printer paper', 'tags': ['office', ...",London,"{'gender': 'F', 'age': 27, 'email': 'zu@bainku...",False,Online
2,5bd761dcae323e45a93ccfec,2017-12-03 18:39:48.253,"[{'name': 'backpack', 'tags': ['school', 'trav...",London,"{'gender': 'M', 'age': 40, 'email': 'dotzu@ib....",False,In store
3,5bd761dcae323e45a93ccfef,2014-03-31 16:02:06.624,"[{'name': 'envelopes', 'tags': ['stationary', ...",Austin,"{'gender': 'M', 'age': 71, 'email': 'man@bob.m...",False,Online
4,5bd761dcae323e45a93ccfed,2015-09-02 16:11:59.565,"[{'name': 'binder', 'tags': ['school', 'genera...",London,"{'gender': 'M', 'age': 44, 'email': 'owtar@pu....",False,In store

## 5) Transform Data

In [12]:
type(df_mongo['items'].iloc[0])

list

In [13]:
df_exploded = df_mongo.explode('items')
df_products = pd.json_normalize(df_exploded['items'])
df_products.head()

        name                             tags   price  quantity
0     laptop    [electronics, school, office]  862.74         4
1  envelopes    [stationary, office, general]    5.04         8
2     binder  [school, general, organization]   11.61         7
3    notepad        [office, writing, school]    5.83         5
4     binder  [school, general, organization]   18.72         2

In [14]:
df_customers = df_sql[['CustomerID', 'Country']].drop_duplicates()
df_customers.columns = ['customer_id', 'country']

In [15]:
df_date = df_sql[['InvoiceDate']].drop_duplicates()

df_date['date_id'] = df_date['InvoiceDate'].astype(str)
df_date['day'] = df_date['InvoiceDate'].dt.day
df_date['month'] = df_date['InvoiceDate'].dt.month
df_date['year'] = df_date['InvoiceDate'].dt.year

In [16]:
df_date.head()

           InvoiceDate              date_id  day  month  year
0  2010-12-01 08:26:00  2010-12-01 08:26:00    1     12  2010
7  2010-12-01 08:28:00  2010-12-01 08:28:00    1     12  2010
9  2010-12-01 08:34:00  2010-12-01 08:34:00    1     12  2010
25 2010-12-01 08:35:00  2010-12-01 08:35:00    1     12  2010
26 2010-12-01 08:45:00  2010-12-01 08:45:00    1     12  2010

In [17]:
df_sql.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34

In [18]:
df_fact = df_sql[['InvoiceNo', 'StockCode', 'CustomerID', 'InvoiceDate', 'Quantity', 'Revenue']]
df_fact.columns = ['order_id', 'product_id', 'customer_id', 'date_id', 'quantity', 'revenue']

In [19]:
df_fact.head()

  order_id product_id  customer_id             date_id  quantity  revenue
0   536365     85123A      17850.0 2010-12-01 08:26:00         6    15.30
1   536365      71053      17850.0 2010-12-01 08:26:00         6    20.34
2   536365     84406B      17850.0 2010-12-01 08:26:00         8    22.00
3   536365     84029G      17850.0 2010-12-01 08:26:00         6    20.34
4   536365     84029E      17850.0 2010-12-01 08:26:00         6    20.34

## 6) Load into Data Warehouse

In [20]:
#Convert collumns into proper types
df_products['tags'] = df_products['tags'].apply(lambda x: ', '.join(x) if isinstance(x, list) else x)
df_products['price'] = df_products['price'].apply(lambda x: float(x.to_decimal()) if x else None)

#Load tables to Data Warehouse
df_products.to_sql('dim_product', engine, if_exists='replace', index=False)
df_customers.to_sql('dim_customer', engine, if_exists='replace', index=False)
df_date.to_sql('dim_date', engine, if_exists='replace', index=False)
df_fact.to_sql('fact_sales', engine, if_exists='replace', index=False)

406829

## 7) SQL Queries

### First run Select all statements for each Table (Generated from MySQL Workbench)

In [21]:
query = """
SELECT `dim_customer`.`customer_id`,
    `dim_customer`.`country`
FROM `retail_data`.`dim_customer`;
"""

df_result = pd.read_sql(query, engine)
df_result.head()

   customer_id         country
0      17850.0  United Kingdom
1      13047.0  United Kingdom
2      12583.0          France
3      13748.0  United Kingdom
4      15100.0  United Kingdom

In [22]:
query = """
SELECT `dim_date`.`InvoiceDate`,
    `dim_date`.`date_id`,
    `dim_date`.`day`,
    `dim_date`.`month`,
    `dim_date`.`year`
FROM `retail_data`.`dim_date`;
"""

df_result = pd.read_sql(query, engine)
df_result.head()

          InvoiceDate              date_id  day  month  year
0 2010-12-01 08:26:00  2010-12-01 08:26:00    1     12  2010
1 2010-12-01 08:28:00  2010-12-01 08:28:00    1     12  2010
2 2010-12-01 08:34:00  2010-12-01 08:34:00    1     12  2010
3 2010-12-01 08:35:00  2010-12-01 08:35:00    1     12  2010
4 2010-12-01 08:45:00  2010-12-01 08:45:00    1     12  2010

In [23]:
query = """
SELECT `dim_product`.`name`,
    `dim_product`.`tags`,
    `dim_product`.`price`,
    `dim_product`.`quantity`
FROM `retail_data`.`dim_product`;
"""

df_result = pd.read_sql(query, engine)
df_result.head()

        name                           tags   price  quantity
0     laptop    electronics, school, office  862.74         4
1  envelopes    stationary, office, general    5.04         8
2     binder  school, general, organization   11.61         7
3    notepad        office, writing, school    5.83         5
4     binder  school, general, organization   18.72         2

In [24]:
query = """
SELECT `fact_sales`.`order_id`,
    `fact_sales`.`product_id`,
    `fact_sales`.`customer_id`,
    `fact_sales`.`date_id`,
    `fact_sales`.`quantity`,
    `fact_sales`.`revenue`
FROM `retail_data`.`fact_sales`
"""

df_result = pd.read_sql(query, engine)
df_result.head()

  order_id product_id  customer_id             date_id  quantity  revenue
0   536365     85123A      17850.0 2010-12-01 08:26:00         6    15.30
1   536365      71053      17850.0 2010-12-01 08:26:00         6    20.34
2   536365     84406B      17850.0 2010-12-01 08:26:00         8    22.00
3   536365     84029G      17850.0 2010-12-01 08:26:00         6    20.34
4   536365     84029E      17850.0 2010-12-01 08:26:00         6    20.34

In [25]:
query = """
SELECT `fact_sales`.`order_id`,
    `fact_sales`.`product_id`,
    `fact_sales`.`customer_id`,
    `fact_sales`.`date_id`,
    `fact_sales`.`quantity`,
    `fact_sales`.`revenue`
FROM `retail_data`.`fact_sales`
"""

df_result = pd.read_sql(query, engine)
df_result.head()

  order_id product_id  customer_id             date_id  quantity  revenue
0   536365     85123A      17850.0 2010-12-01 08:26:00         6    15.30
1   536365      71053      17850.0 2010-12-01 08:26:00         6    20.34
2   536365     84406B      17850.0 2010-12-01 08:26:00         8    22.00
3   536365     84029G      17850.0 2010-12-01 08:26:00         6    20.34
4   536365     84029E      17850.0 2010-12-01 08:26:00         6    20.34

In [26]:
query = """
SELECT `online_retail`.`StockCode`,
    `online_retail`.`Description`,
    `online_retail`.`Quantity`,
    `online_retail`.`InvoiceDate`,
    `online_retail`.`UnitPrice`,
    `online_retail`.`CustomerID`,
    `online_retail`.`Country`,
    `online_retail`.`Revenue`
FROM `retail_data`.`online_retail`;
"""

df_result = pd.read_sql(query, engine)
df_result.head()

,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue
0,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
2,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00
3,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
4,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34

### Next, run more complex SQL queries to show functionality

#### Get Revenue per Year in Descending Order

In [27]:
query = """
SELECT d.year, SUM(f.revenue) AS total_revenue
FROM fact_sales f
JOIN dim_date d ON f.date_id = d.date_id
GROUP BY d.year
ORDER BY d.year DESC;
"""

df_result = pd.read_sql(query, engine)
df_result.head()

   year  total_revenue
0  2011   7.745462e+06
1  2010   5.546040e+05

#### Get Average Quantity Sold Each Year

In [30]:
query = """
SELECT d.year, SUM(o.Quantity) AS total_quantity
FROM online_retail o
JOIN dim_date d ON o.InvoiceDate = d.InvoiceDate
GROUP BY d.year
ORDER BY d.year DESC;
"""

df_result = pd.read_sql(query, engine)
df_result.head()

   year  total_quantity
0  2011       4610526.0
1  2010        296362.0

#### Get Average Revenue

In [29]:
query = """
SELECT AVG(revenue) AS avg_order_value
FROM fact_sales;
"""
df_result1 = pd.read_sql(query, engine)
df_result1.head()

   avg_order_value
0        20.401854

In [28]:
query = """
SELECT AVG(price * quantity) AS avg_order_value
FROM dim_product;
"""

df_result2 = pd.read_sql(query, engine)
df_result2.head()

   avg_order_value
0       360.615652

### Data
- SQL Database - `https://github.com/trajev/restaurant-mysql-project`
- NoSQL Database = `https://www.mongodb.com/docs/atlas/sample-data/sample-restaurants/#std-label-sample-restaurants`

 
Atlas Cluster: https://cloud.mongodb.com/v2/69bf4e04a0132f9d6aabbb6b#/clusters